/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaCityChina: typeof import('./../components/areaCityChina.vue')['default']
    AreaCityChina2: typeof import('./../components/areaCityChina2.vue')['default']
    AutoUploadFile: typeof import('./../components/autoUploadFile.vue')['default']
    CommonForms: typeof import('./../components/common/forms.vue')['default']
    CommonPopup: typeof import('./../components/common/popup.vue')['default']
    CommonProgress: typeof import('./../components/common/progress.vue')['default']
    CommonUniForm: typeof import('./../components/common/uniForm.vue')['default']
    ExpensesPopup: typeof import('./../components/expensesPopup.vue')['default']
    MothPicker: typeof import('./../components/mothPicker.vue')['default']
    UniForm: typeof import('./../components/uniForm.tsx')['default']
  }
}

// For TSX support
declare global {
  const AreaCityChina: (typeof import('./../components/areaCityChina.vue'))['default']
  const AreaCityChina2: (typeof import('./../components/areaCityChina2.vue'))['default']
  const AutoUploadFile: (typeof import('./../components/autoUploadFile.vue'))['default']
  const CommonForms: (typeof import('./../components/common/forms.vue'))['default']
  const CommonPopup: (typeof import('./../components/common/popup.vue'))['default']
  const CommonProgress: (typeof import('./../components/common/progress.vue'))['default']
  const CommonUniForm: (typeof import('./../components/common/uniForm.vue'))['default']
  const ExpensesPopup: (typeof import('./../components/expensesPopup.vue'))['default']
  const LedgerPopup: (typeof import('./../components/ledgerPopup.vue'))['default']
  const MothPicker: (typeof import('./../components/mothPicker.vue'))['default']
  const Popup: (typeof import('./../components/popup.vue'))['default']
  const UniForm: (typeof import('./../components/uniForm.tsx'))['default']
}
